/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagIdRouteImport } from './routes/tags.$tagId'
import { Route as ReaderDocIdRouteImport } from './routes/reader.$docId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderDocIdRoute = ReaderDocIdRouteImport.update({
  id: '/reader/$docId',
  path: '/reader/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/reader/$docId': typeof ReaderDocIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/reader/$docId': typeof ReaderDocIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/reader/$docId': typeof ReaderDocIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/reader/$docId' | '/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/reader/$docId' | '/tags/$tagId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/reader/$docId'
    | '/tags/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ReaderDocIdRoute: typeof ReaderDocIdRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$docId': {
      id: '/reader/$docId'
      path: '/reader/$docId'
      fullPath: '/reader/$docId'
      preLoaderRoute: typeof ReaderDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ReaderDocIdRoute: ReaderDocIdRoute,
  TagsTagIdRoute: TagsTagIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
